### ISSUE TITLE
Tool Purpose

### ISSUE THREAD

**Issue by michael36020** [dreddsa5dies/goHackTools#42]
Hello there, I would like to know what this tool can be used for and how I can expand it's possibilities.

**Comment by hazcod** [comment]
It's a repository containing a collection of tools.

**Comment by dreddsa5dies** [comment]
Welcomes any kind of contribution, please read how to write GO code and follow the next steps:

Fork the project on github.com.
Create a new branch.
Commit changes to the new branch.
Send a pull request.
