### ISSUE TITLE
GOMAXPROCS

### ISSUE THREAD

**Issue by Amirkin** [dreddsa5dies/goHackTools#6]
`runtime.GOMAXPROCS(runtime.NumCPU())`

Это нужно было делать до версии 1.5.
Более новые версии сразу устанавливают MAXPROCS по количеству процессорных потоков.

**Comment by dreddsa5dies** [comment]
Спасибо, читал об этом. Исправлю в ближайшее время

**Comment by dreddsa5dies** [comment]
[https://github.com/dreddsa5dies/goHackTools/pull/7/commits/3e6f9ca830654c16f79ac4295435374c96df7175](Rectification issue)

**Comment by dreddsa5dies** [comment]
[Rectification issue](https://github.com/dreddsa5dies/goHackTools/pull/7/commits/3e6f9ca830654c16f79ac4295435374c96df7175)
